[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "py_steelseries_sonar"
version = "1.0.0"
readme = "README.md"
dependencies = ["requests"]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["py_steelseries_sonar"]